### ISSUE TITLE
ORM

### ISSUE THREAD

**Issue by Wemago** [xeoncross/1kb-PHP-MVC-Framework#2]
Using ORM how is possible to do where conditions? Would like to join OR and AND but from what I see from the where function it only works with AND.

I have a class Users that extends ORM and I can't seem to get to $user->fetch() or $user->query().

**Comment by xeoncross** [comment]
Yes, the ORM only supports `AND` in `WHERE` clauses. I recomend you run the query directly and then loop over it and create your objects.

```
$myobjects = array();
foreach($result as $row) {
    $myobjects[] = new MyModel($row);
}
```

Also, you can use the [ORM::get() method](https://github.com/Xeoncross/1kb-PHP-MVC-Framework/blob/master/classes/orm.php#L11) too.

```
var_dump($myModel->get(array('foo' => 'bar')));
```

I really don't recommend you use this project though. I would Try MicroMVC or Laravel since this was just a fun project that isn't full-featured enough for real-world sites.
